
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-01-11T14:44:59+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "b299064bdb315265f9140af381846e449ee75693",
 "version": "0.9.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
